// import { RouteConfigType } from '@/types/routes'

const routes = {
  home: '/',
  signIn: '/sign-in',
  signUp: '/sign-up',
  feed: '/feed',
  community: '/community',
  notification: '/notifications',
  explore: '/explore',
  settings: '/settings',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-pass',
  checkEmail: '/email-verification',
  notVerifyEmail: '/not-verify-email',
  about: '/about',
  contact: '/contact',
  serverError: '/server-error',
  forbidden: '/forbidden',
  consultationStandard: '/consultation/standard',
  consultationPremium: '/consultation/premium',
  productFlashSale: '/flash-sale',
  recommendProducts: '/products/recommend-products',
  helpCenter: '/portal',
  products: '/products',
  productDetail: '/products/:productId',
  productReview: '/products/:productId/review',
  profileWishlist: '/profile/wishlist',
  profile: '/profile',
  profileAddress: '/profile/address',
  profileOrder: '/profile/order',
  profileOrderDetail: '/profile/order/:orderId',
  profilePassword: '/profile/password',
  profileNotification: '/profile/notification',
  profileVoucher: '/profile/voucher',
  blogs: '/blogs',
  privacyPolicy: '/privacy-policy',
  termsAndConditions: '/terms-and-condition',
  cart: '/cart',
  checkout: '/checkout',
  checkoutResult: '/checkout/result',
  sellLanding: '/landing/sell',
  professionalLanding: '/landing/professional',
  search: '/search',
  brands: '/brands',
  brandDetail: '/brands/:brandId',
  notFound: '*',
}

export default routes
